### PR TITLE
Updated package's codes to rely on Livewire's config() view_path

### PR DESCRIPTION
**Pull request by hamzaelmaghari**

### CODE REVIEW

**Comment by nunomaduro** [comment]
@hamzaelmaghari plz keep this on draft.

**Comment by hamzaelmaghari** [comment]
@nunomaduro Okay 👌

**Comment by mybouhssina** [comment]
+1 for this !

**Comment by nunomaduro** [comment]
The idea is good, but the code is not correct. Replaced by https://github.com/livewire/volt/pull/85.

**Pull request closed without merging**
